### ISSUE TITLE
Login and Logout not open metamask

### ISSUE THREAD

**Issue by Alberto-00** [Edoumou/blockchain-based-authentication#2]
Hello, when I try to login or logout, metamask doesn't open to verify credentials and the error message doesn't appear when I put an user that didn't register.
Can you help me?

**Comment by Edoumou** [comment]
Hello,

If you can't login or logout, then make sure

- to deploy the contract before interacting with the Dapp
- to run __npm i__
- Also try to remove package-lock.json

If the above can't solve the problem, just tell me we will manage it working together

**Comment by Alberto-00** [comment]
Hello,
To deploy the contract before, with **npm i** and then **npm run start**, the Dapp show error message "Failed to load Web3" so I start ganache and metamask and Dapp run correctly but login and logout doesn't work: errors message don't appear (if i wrong user or password or I try to registry an existing user) and don't add new user in metamask.

**Comment by Edoumou** [comment]
Hello @Alberto-00 

Ok, I can help you make it run. Just let me  know when you're available so as I can help.

You can contact me through my LinkedIn: [https://www.linkedin.com/in/samuel-ongala-edoumou](https://www.linkedin.com/in/samuel-ongala-edoumou)

**Comment by Alberto-00** [comment]
Hello @Edoumou 

I invited you on linkedin but i can't send you messages. Anyway I still have the same problem.

**Comment by Edoumou** [comment]
I've just sent you a message
